# Server
server.port=8080

# App name
spring.application.name=api-gateway

# Eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable discovery-based routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Routes (manual)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=post-service
spring.cloud.gateway.routes[1].uri=lb://post-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/posts/**

spring.cloud.gateway.routes[2].id=comment-service
spring.cloud.gateway.routes[2].uri=lb://comment-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/comments/**

# STATIC FILE ROUTE (ADD THIS)
spring.cloud.gateway.routes[3].id=post-static
spring.cloud.gateway.routes[3].uri=lb://post-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/uploads/**