# Server Port
server.port=8761

# Application Name
spring.application.name=eureka-server

# Eureka Config
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Optional (cleaner logs)
eureka.server.enable-self-preservation=false